### PR TITLE
Add in rms plot in auto_view.py

### PR DESCRIPTION
**Pull request by zakiali**
Iv'e added in the a function for the plot. Let me know if that function should live somewhere else other than the script itself. Also, if there are any style modifications to be made.

### CODE REVIEW

**Comment by zakiali** [comment]
This is the generated plot for one polarization 
zen 2458001 11719 xx auto_rms_values

**Comment by nkern** [comment]
@zakiali might be useful to put in the title which polarization in that case.. and perhaps make antenna text a color other than black..

**Comment by zakiali** [comment]
better?
zen 2458001 11719 xx auto_rms_values

**Comment by adampbeardsley** [comment]
@nkern Did you have any other comments on this one before we merge?

**Pull request merged**
