### PR TITLE
MC compatibility imports

### LINKED ISSUE #199: Downgrade hera_cal import
In the recent ant metrics revamp, we switched over to using HERAData instead of UVData. But this adds a top level dependency, which broke hera_mc tests. If possible, we should downgrade this import so it's not done by default.

https://github.com/HERA-Team/hera_qm/blob/f654459f0f2d3453feacbab6143719458ec1a74d/hera_qm/ant_metrics.py#L15

### PR DESCRIPTION
**Pull request by mkolopanis**
Moved some imports to help [hera_mc](https://github.com/HERA-Team/hera_mc) import this package without need for  [hera_cal](https://github.com/HERA-Team/hera_cal) .

@bhazelton  is helping to test the compatibility. 

fixes #199 

Let's wait to merge into master in case there are additional changes to be made.

### CODE REVIEW

**Comment by bhazelton** [comment]
This appears to fix the problem for me. Thank you!

**Comment by bhazelton** [comment]
It looks like the Travis build passed, not sure why it hasn't reported that back to github...

**Comment by mkolopanis** [comment]
well we've _never_ had issues with travis before.

**Comment by mkolopanis** [comment]
even command line merging seems to be blocked. something clogged the tubes between github and travis i guess

**Comment by bhazelton** [comment]
if you want to force it, you need to turn off the `required statuses must pass` line on the branch protection on github

**Comment by plaplant** [comment]
Looks like it's a known issue that travis and github aren't currently talking to each other: https://www.traviscistatus.com/

**Comment by bhazelton** [comment]
Arg! Thanks @plaplant. The universe is out to get me today.

**Comment by mkolopanis** [comment]
Good find. Looks like we should check the status page more :stuck_out_tongue:  If it is mission critical we can do a force merge.

**Comment by bhazelton** [comment]
It's not mission critical. It's preventing merging an M&C PR to control node power on site, but a delay won't ruin anything. I'd been trying to get it working while Jack was on site, but he's gone now anyway.

**Comment by bhazelton** [comment]
And the M&C PR will also be affected by the Travis - github communication issues.

**Comment by adampbeardsley** [comment]
Now that travis finally updated, we get the "Required statuses must pass before merging" message. When I tried forcing the push via command line, it thinks there are no approving reviews.
```(HERA) clancy:hera_qm abeardsley$ git push origin master
Counting objects: 1, done.
Writing objects: 100% (1/1), 234 bytes | 234.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0)
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access.
To github.com:HERA-Team/hera_qm.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:HERA-Team/hera_qm.git'
```
Maybe I can't be the approver and the pusher? Can someone else try?

**Comment by bhazelton** [comment]
Thank you @adampbeardsley @mkolopanis !

**Pull request merged**
