### PR TITLE
Close figures after saving them

### PR DESCRIPTION
**Pull request by plaplant**
This PR addresses Issue #84. The warning appears to have gone away from Travis, which means things are more memory-friendly for end-users as well.

### CODE REVIEW

**Comment by nkern** [comment]
@plaplant To fix the tests, I've just been doing `plt.close()` after a test involving a plotting routine to close all open plots, which has solved the travis issue in the past.

One might think of a situation where I'm using a notebook to make a plot, but also want to write the plot out to file w/ the `save` keyword at the same time. If we close the figure in the script, we won't be able to do both at the same time. 

One can think of an easy way around this (just run the script twice, one w/ `save=False` and `save=True'). I'm fine w/ this fix but just something to consider...

**Comment by plaplant** [comment]
If it's easier to just add a `plt.close()` statement to the tests, that's fine with me. I'll roll back these changes and try that instead.

**Comment by nkern** [comment]
@plaplant yeah I did it in `test_omnical_metrics`, but I must have forgotten to do it in `test_firstcal_metrics`. thanks

**Comment by plaplant** [comment]
@nkern this PR should be ready for another look

**Comment by nkern** [comment]
@plaplant looks good!

**Pull request merged**
